@startuml factory
scale 1

interface Builder{
    reset()
    builderStepA()
    builderStepB()
    builderStepC()
}
' ' hide Human field

class ConcreteBuilder1{
    result Product1
    reset()
    builderStepA()
    builderStepB()
    builderStepC()
    getResult() Product1
}

class ConcreteBuilder2{
    result Product1
    reset()
    builderStepA()
    builderStepB()
    builderStepC()
    getResult() Product1
}

Builder <|.. ConcreteBuilder1
Builder <|.. ConcreteBuilder2

class Director{
    builder Builder
    Director(builder)
    changeBuilder(builder)
    make(type)
}

Director .left.> Builder

@enduml