@startuml factory
scale 1

interface Product{}

interface Creator{
    FactoryMethod()
}

class ConcreteProduct{}

class ConcreteCreator{}

Product <|.. ConcreteProduct
Creator <|.. ConcreteCreator

ConcreteProduct <-right- ConcreteCreator

@enduml
